### ISSUE TITLE
offline install with simplified Chinese become garbled text

### ISSUE THREAD

**Issue by qaws68** [Jineapple/WololoKingdoms#32] opened 2017-12-18 13:48 UTC
Hi Jineapple. I come from Taiwan where we use Traditional Chinese. In our system, simplified Chinese  will become garbled text: https://imgur.com/PVii7sh https://imgur.com/SwaSwgZ . I made WololoKingdoms  with  Traditional Chinese version by myself that used files ( https://goo.gl/8dWMLC from http://steamcommunity.com/sharedfiles/filedetails/?id=466768643 )(officially recommended with Traditional Chinese version only) to replace files in Age2HD\resources\zh and 
modified language.ini to traditional Chinese version : https://goo.gl/GpyXUB. But when language_x1_p1.dll creates WK.exe  I can't modify language.ini into Traditional Chinese version with offline installation,. Can you help Traditional Chinese players? Would you please create a new language version using the hyperlinks providing above? I will be grateful for any help you provide. Thanks a million.

**Comment by Jineapple** [comment] 2017-12-19 14:20
It's something I can look into, but I'm going to need more information on what exactly you tried.

If I understand you correctly, you replaced C:\Program Files (x86)\Steam\steamapps\common\Age2HD\resources\zh\strings\key-value\key-value-strings-utf8.txt with a Traditional Chinese version and then ran the WK installer with Simplified Chinese selected as the language, is that correct?

And this worked when playing WK through Voobly, but did not work offline?

**Comment by qaws68** [comment] 2017-12-19 14:27
exactly!

**Comment by Jineapple** [comment] 2017-12-20 15:31
Not sure why it would create the language.ini correctly, but not the dll...
What's the issue with the offline version exactly? Is it just blank, or are there characters but they are wrong? In what way?

**Comment by qaws68** [comment] 2017-12-20 15:59
In offline version, It will creates new simplified Chinese language.ini first, then creates dll and WK.exe. I replace language.ini is not work. offline version issue is simplified Chinese in Traditional Chinese system encoded is often blank and garbled.

**Comment by Jineapple** [comment] 2017-12-20 17:29
Sorry, I'm not sure if I understand. If offline installation is selected, the created language.ini is simplified chinese, even though the HD text file was replaced? So the \Games\WololoKingdoms\language.ini is simplified chinese, but the \Voobly Mods\AOC\Data Mods\WololoKingdoms is traditional chinese?

**Comment by qaws68** [comment] 2017-12-21 01:18
In offline version, step1:  create new simplified Chinese language.ini, step 2: use step 1 ini to create dll, step 3: create WK.exe, then when WK.exe is running, It will reading dll at same time. So dll is most important file in offline version language. In simplified Chinese offline version, dll is simplified Chinese. So in offline version, I replaced ini before offline installation or replaced after offline installation is not work. If It want to be traditional chinese  offline version, dll need to be traditional chinese already in installation steps. 

In normal version, it creates new simplified Chinese language.ini same, but I can replaced ini after installation. When playing WK through Voobly,  It is just reading ini at same time.

I hope my description would help! Thank you.

**Comment by keypol** [comment] 2017-12-21 03:09
Hello, I'm also a user that use Traditional Chinese as default language in Windows.  

Let's describe it from a user's perspective,
Many of us follow qaws68's tutorial to first install WololoKingdoms, then we replace
\Voobly Mods\AOC\Data Mods\WololoKingdoms\language.ini
\Voobly Mods\AOC\Data Mods\WololoKingdoms FE\language.ini
\Voobly Mods\AOC\Data Mods\WololoKingdoms AK\language.ini
with qaws68's custom edition, in that way, 
the game will display in Traditional Chinese through Voobly when WK is selected.

However, if we open the "\Age2HD\age2_x1\WK.exe" directly, the language there will remain 
the one we select here https://i.imgur.com/uEAmJKR.png
which means that when we choose "English/Simplified Chinese" , the offline version will always remain to be "English/Simplified Chinese" whether we modify language.ini or not.

The garbled language has done nothing with your codes, it's just because of some compatibility problem that happens when non-unicode Simplified Chinese appears in Traditional Chinese system.

After all, a lot of thanks for you to create this WololoKingdoms, without it, we can't use these civs in Voobly.  But we really hope that you can help us create a new "Traditional Chinese (繁體中文)" to select during installation, and by choosing it, we can have things displaying correctly in both Voobly and offline. Lots of thanks!

**Comment by Jineapple** [comment] 2017-12-21 14:20
Thank you abelyi. Changing the language.ini has no effect on the language_x1_p1.dll used offline, so that is expected. However, could you try if it works offline if you

1. Replace the key-value-strings-utf8.txt in Age2HD/resources/zh/strings/key-value
2. Then run the installer with simplified chinese selected

I can definitely add an option for traditional chinese, but I need to know if the above method works. I think it should, because selecting simplified chinese just means the installer looks in the "zh" folder for the language files. If those are replaced with the traditional chinese ones, the game should also be in traditional chinese. If that's not the case, I'll need to figure out why that's happening.

**Comment by keypol** [comment] 2017-12-21 15:27
Nope, the game still displays in garbled text.  And guess what?  The garbled text created by the installer with the two different strings(Simplified and Traditional) are also different lol.
https://i.imgur.com/WagJrcK.jpg

P.S. Though the Chinese characters are garbled, English still displays normally, as you can see this link , which qaws68 gives you. https://imgur.com/SwaSwgZ

**Comment by qaws68** [comment] 2017-12-21 17:47
It's still garbled text like abelyi description and pictures he provides, and I didn't find the reason. language.ini is changed to Traditional, but still garbled.
Maybe it's already Traditional, but displays encode issue to become garbled or something else issues.

offline english version, displays seems a little issue https://i.imgur.com/2O8mg9b.png. My voobly is hd to voobly version. I do not know it's related or not.

**Comment by Jineapple** [comment] 2017-12-21 22:25
Hmm okay that means it's not a simple fix unfortunately. I'll include an attempt at it in the next installer, and you can tell me if it works or not.

**Comment by qaws68** [comment] 2017-12-22 04:36
Thank you! We hope to hear favourably from you.

**Comment by Jineapple** [comment] 2018-01-02 09:29
I uploaded a new version now, with two experimental settings for Traditional Chinese - let me know if one works for you.

**Comment by keypol** [comment] 2018-01-02 11:02
None of them works, both displays the same garbled text.
https://i.imgur.com/ihayT01.png

However I found something really strange this time.  The description of the "Single Player->Watching Player" option shows Traditional Chinese.  But it's only that description, all the other descriptions still display in garbled text.  And this happens when I choose "Simplified Chinese, TC test1 and TC test2" during installation.
https://i.imgur.com/PU6S8JJ.png
If I choose English, that description came back to be in English.
https://i.imgur.com/e02dHcI.png

BTW, there's a warning while the installer is applying DAT patches, saying that the version I use isn't the same with the Steam live version.  Therefore I can't play rated games, I don't actually know how to solve it...

**Comment by qaws68** [comment] 2018-01-06 07:29
I think it's encode issue. I use Resource Hacker to open dll, it's full of garbled text. And I fix some text to  Traditional Chinese directly, It's will become Traditional Chinese in game. https://i.imgur.com/OwEuvbd.jpg https://i.imgur.com/4nUdNgV.jpg

**Comment by Jineapple** [comment] 2018-01-07 14:21
Yes it's an encoding issue for sure. The problem is that I don't know how to get the encoding right. It's not a subject I'm very familiar with and it also depends on external libraries :|

**Comment by qaws68** [comment] 2018-02-25 04:36
Hi Jineapple, I think test 1 and test 2 can both work on  for version 5.7 with Traditional Chinese. Thanks for your help! But it still needs to be modified in every new patch. In fact in version 5.7 zht resources is version 5.6.
I think it can be modified by Traditional Chinese players themselves to renew resources from Steam Workshop. Maybe you can  just provide operational steps for them.

steps are as follows:
1. subscribe Traditional Chinese Workshop
http://steamcommunity.com/sharedfiles/filedetails/?id=466768643
2. go to folder:
steamapps\workshop\content\221380\466768643\resources\zh\strings
3. copy "history folder" and "key-value-strings-utf8.txt" to  folder  "WololoKingdoms.5.7\WololoKingdoms 5.7\resources\zht" replace files
4. run WololoKingdoms.exe


Traditional Chinese translation steps:
1.訂閱小汝繁中的工作坊
http://steamcommunity.com/sharedfiles/filedetails/?id=466768643
2.到工作坊資料夾:
steamapps\workshop\content\221380\466768643\resources\zh\strings
3.複製裡面的history資料夾與key-value-strings-utf8.txt
然後到wk安裝檔的資料夾內 WololoKingdoms.5.7\WololoKingdoms 5.7\resources\zht
取代裡面的history資料夾與key-value-strings-utf8.txt
4.再執行WololoKingdoms.exe 安裝檔

**Comment by Jineapple** [comment] 2018-05-22 15:57
Hey, sorry for not replying sooner. Good to hear that the tests work! Updating the files shouldn't be much of an issue, I need to push an update whenever there's a new steam release anyway.

As this should be solved then, I will close the issue

**Closed as completed by Jineapple** 2018-05-22 15:57 UTC
